apiVersion: v1
kind: Service
metadata:
  name: {{ include "unigate.fullname" . }}-svc
  namespace: {{ include "unigate.namespace" . }}
  labels:
    {{- include "unigate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "unigate.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
